title: "Top Scores, Top Floors, and Top Whores"
email: the.software.shinobi@gmail.com
timezone: BOG
baseurl: "/"
permalink: none
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
#disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Vida De Avion
    display_name: Vida De Avion
    avatar: 'assets/images/sal.png'
    web: https://www.wowthemes.net/category/jekyll-themes/
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

  john:
    name: Vida De Avion
    display_name: Vida De Avion
    avatar: 'assets/images/sal.png'
    web: https://www.wowthemes.net/category/jekyll-themes/
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

## Social

social:

  instagram: https://www.instagram.com/mateo.taganga/

##  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
##  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
